---
# Manually install/upgrade roles and collections using the following commands.
#   ansible-galaxy collection install --upgrade -r galaxy/requirements.yml
#   ansible-galaxy role install --upgrade -r galaxy/requirements.yml
# List the roles/collections that currently exist (useful to cleanup)
#   ansible-galaxy collection list
#   ansible-galaxy role list
# Clean existing collections:
#   rm -rf galaxy/ansible_collections/*
# More info can be found here: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
# Tips:
# - Galaxy User Guide
#   https://docs.ansible.com/ansible/latest/galaxy/user_guide.html
# - Installing Roles and Collections from the same requirements file
#   https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-a-file
# - Installing multiple roles from multiple files
#   https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-multiple-files
# - Installing multiple roles from a file
#   https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-a-file
# - Use the `scm` key for repos that do not exist in ansible-galaxy.com!

# Use the `include` module here can greatly help breakup the collections/roles into
# those specific to what needs the collection/roles. It has the following benefits:
# - Allows running `ansible-galaxy` on just a subset of roles instead of the full `requirements.yml`
#   which will grow over time.
# - Groups roles/collections that belong to a specific functional area
# - Makes it easier to remove roles/collections by knowing the scope of its use

collections:
- include: collections-general.yml

roles:
- include: roles-application.yml
- include: roles-web.yml
- include: roles-database.yml
- name: role-template
  src: https://github.com/ansiblejunky/ansible-role-template.git
  version: master
  scm: git
