all:
  children:
    # Use shared group names between test/staging/prod but switch out the hosts between enviornments to roll out the same config on the e.g test loadbalancers and now on the prod loadbalancers
    ingress:
      loadbalancer-prod-01:
    # Use the same group names as your test enviornment
    webservers:
      hosts:
        prod-webserver1:
        prod-webserver2:
    dbservers:
      hosts:
        prod-dbserver1:
        prod-dbserver2:
