- name: Update system packages
  hosts: all
  become: true
  tasks:
    - name: Ensure all packages are up to date
      dnf:
        name: "*"
        state: latest

# These playbooks should be short and only be used for one-time-actions. Don't build any complexe logic here! 